import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Notification from '@/components/Notification';
import NavBar from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Food',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notification />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
